# Generated by Django 4.2 on 2023-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
    ]
